### ISSUE TITLE
Recent versions of JSLint don't work with wrapper

### ISSUE THREAD

**Issue by AlbertWiersch** [douglascrockford/JSLint#246]
Need some help from a JavaScript genius.

Recent versions (sometime after version 2018-04-25) of JSLint have stopped working with a wrapper.js script I am using.

Any ideas? Do I need to change my wrapper script? If so, then how?

Thanks!

```
T:\nodejs>node.exe wrapper.js --browser=true --devel=true --maxerr=30 --white=true --this=true "jstest.js"
evalmachine.<anonymous>:4837
export default Object.freeze(function jslint(
^^^^^^

SyntaxError: Unexpected token export
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInNewContext (vm.js:296:10)
    at doLint (T:\nodejs\wrapper.js:111:6)
    at main (T:\nodejs\wrapper.js:121:14)
    at Object.<anonymous> (T:\nodejs\wrapper.js:251:1)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
```

**Comment by EvgenyOrekhov** [comment]
Node's support for ES6 modules is experimental. You'd have to fiddle with its CLI options and file extensions. Man page: https://nodejs.org/api/esm.html.

**Comment by kaizhu256** [comment]
hi @AlbertWiersch, there was a rejected pull-request to add commandline-wrapper for jslint,  https://github.com/douglascrockford/JSLint/pull/233 which does exactly what you wanted.

here's an updated version of the wrapper from that pull-request (to work with latest jslint), and attached screenshot showing wrapper jslinting local and remote/http files from shell

![image](https://user-images.githubusercontent.com/280571/45597388-a4559b80-b9f5-11e8-8c16-bb44734fae7e.png)

```
#!/usr/bin/env node

/*
 * cli.js
 * commandline wrapper for jslint
 */

/*jslint node */
/*property
    argv, basename, column, concat, end, error, exit, filter, forEach, fudge,
    join, jslint, line, lines, main, match, message, on, option, parse, push,
    readFile, replace, request, runInNewContext, slice, trim, trimRight,
    warnings
*/
"use strict";
let chunk_list;
let file;
let fs;
let fudge;
let local;
let modeNext;
let onNext;
let path;
let url;
let vm;
let warning_text;
onNext = function (error, data) {
    if (error) {
        console.error(error.message || error);
        process.exit(1);
    }
    modeNext += 1;
    switch (modeNext) {
    case 1:
        // run this program only in cli-mode
        if (module !== require.main) {
            console.error(
                "jslint-cli can only be run from the command-line"
            );
            return;
        }
        // require builtins
        fs = require("fs");
        path = require("path");
        url = require("url");
        vm = require("vm");
        // init local namespace
        local = { module: {} };
        if (!process.argv[2]) {
            console.error(
                "error:   no <file/url> specified\n"
                + "usage:   " + path.basename(__filename) + " <file/url>\n"
                + "example: " + path.basename(__filename) + " example.js\n"
                + "example: " + path.basename(__filename)
                + " https://jslint.com/jslint.js"
            );
            process.exit(1);
        }
        // init jslint
        fs.readFile(path.join(__dirname, "jslint.js"), "utf8", onNext);
        break;
    case 2:
        // bug-workaround - nodejs does not widely support es-modules
        vm.runInNewContext(
            data.replace(
                "export default Object.freeze(function",
                "module.exports = (function"
            ),
            local
        );
        local.jslint = local.module.exports;
        // read data from file
        file = process.argv[2];
        console.error("jslint " + file);
        data = file.match(/^(https?):\/\//);
        if (!data) {
            fs.readFile(file, "utf8", onNext);
            return;
        }
        // read data from http/https url
        require(data[1]).request(url.parse(file), function (response) {
            chunk_list = [];
            response
            .on("data", function (chunk) {
                chunk_list.push(chunk);
            })
            .on("end", function () {
                onNext(null, String(Buffer.concat(chunk_list)));
            })
            .on("error", onNext);
        }).on("error", onNext).end();
        break;
    case 3:
        // jslint data
        data = local.jslint(data
        // ignore first-line shebang in nodejs scripts
        .replace((/^#!/), "//"));
        fudge = data.option.fudge || 0;
        // init warning_text
        warning_text = "";
        // print warnings to stderrr
        data.warnings
        .filter(function (warning) {
            return warning && warning.message;
        })
        // print only first 10 warnings
        .slice(0, 10)
        .forEach(function (warning, ii) {
            warning_text += (
                (" #" + (ii + 1)).slice(-3)
                + " \u001b[31m" + warning.message + "\u001b[39m\n"
                + "    " + String(data.lines[warning.line] || "").trim()
                + "\u001b[90m \/\/ line "
                + (warning.line + fudge)
                + ", col " + (warning.column + fudge)
                + "\u001b[39m\n"
            );
        });
        console.error(warning_text.trimRight() || "ok");
        break;
    }
};
modeNext = 0;
onNext();
```

**Comment by AlbertWiersch** [comment]
> hi @AlbertWiersch, there was a rejected pull-request to add commandline-wrapper for jslint, #233 which does exactly what you wanted.
> 
> here's an updated version of the wrapper from that pull-request (to work with latest jslint), and attached screenshot showing wrapper jslinting local and remote/http files from shell

Thanks! That was extremely helpful. That wrapper helped me re-write my current wrapper to work with the recent versions of **JSLint**.
